parameters:
#    taxi_admin_sitio.example.class: TaxiAdmin\SitioBundle\Example

services:
#    taxi_admin_sitio.example:
#        class: %taxi_admin_sitio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
