<?php


/**
 * This class defines the structure of the 'trabajoTaller' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun May 26 12:23:25 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TrabajotallerTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TrabajotallerTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('trabajoTaller');
		$this->setPhpName('Trabajotaller');
		$this->setClassname('Trabajotaller');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('IDMOVIL', 'Idmovil', 'INTEGER', 'movil', 'ID', true, null, null);
		$this->addForeignKey('IDTALLER', 'Idtaller', 'INTEGER', 'taller', 'ID', true, null, null);
		$this->addColumn('FECHAINGRESO', 'Fechaingreso', 'DATE', false, null, null);
		$this->addColumn('MOTIVOINGRESO', 'Motivoingreso', 'VARCHAR', false, 200, null);
		$this->addColumn('COSTOMATERIALES', 'Costomateriales', 'DECIMAL', false, 17, null);
		$this->addColumn('COSTOMANOOBRA', 'Costomanoobra', 'DECIMAL', false, 17, null);
		$this->addColumn('DETALLETRABAJO', 'Detalletrabajo', 'VARCHAR', false, 200, null);
		$this->addColumn('RESPONSABLE', 'Responsable', 'VARCHAR', false, 150, null);
		$this->addColumn('TIPOPAGO', 'Tipopago', 'VARCHAR', false, 150, null);
		$this->addColumn('TOTALTRABAJO', 'Totaltrabajo', 'DECIMAL', false, 17, null);
		$this->addColumn('NUMEROFACTURA', 'Numerofactura', 'VARCHAR', false, 50, null);
		$this->addColumn('FECHAALTA', 'Fechaalta', 'TIMESTAMP', true, null, null);
		$this->addColumn('FECHABAJA', 'Fechabaja', 'TIMESTAMP', false, null, null);
		$this->addColumn('HABILITADO', 'Habilitado', 'BOOLEAN', false, null, true);
		$this->addForeignKey('USUARIO', 'Usuario', 'INTEGER', 'usuario', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Movil', 'Movil', RelationMap::MANY_TO_ONE, array('idMovil' => 'id', ), 'CASCADE', null);
    $this->addRelation('Taller', 'Taller', RelationMap::MANY_TO_ONE, array('idTaller' => 'id', ), 'CASCADE', null);
    $this->addRelation('UsuarioRelatedByUsuario', 'Usuario', RelationMap::MANY_TO_ONE, array('usuario' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TrabajotallerTableMap
