<?php

/**
 * Base class that represents a row from the 'accidente' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Oct  6 14:44:38 2012
 *
 * @package    lib.model.om
 */
abstract class BaseAccidente extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AccidentePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the idchofer field.
	 * @var        int
	 */
	protected $idchofer;

	/**
	 * The value for the idmovil field.
	 * @var        int
	 */
	protected $idmovil;

	/**
	 * The value for the fecha field.
	 * @var        string
	 */
	protected $fecha;

	/**
	 * The value for the responsable field.
	 * @var        string
	 */
	protected $responsable;

	/**
	 * The value for the esquina field.
	 * @var        string
	 */
	protected $esquina;

	/**
	 * The value for the heridos field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $heridos;

	/**
	 * The value for the deducible field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $deducible;

	/**
	 * The value for the descripcion field.
	 * @var        string
	 */
	protected $descripcion;

	/**
	 * The value for the fechaalta field.
	 * @var        string
	 */
	protected $fechaalta;

	/**
	 * The value for the fechabaja field.
	 * @var        string
	 */
	protected $fechabaja;

	/**
	 * The value for the habilitado field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $habilitado;

	/**
	 * The value for the usuario field.
	 * @var        int
	 */
	protected $usuario;

	/**
	 * @var        Chofer
	 */
	protected $aChofer;

	/**
	 * @var        Movil
	 */
	protected $aMovil;

	/**
	 * @var        Usuario
	 */
	protected $aUsuarioRelatedByUsuario;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'AccidentePeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->heridos = 0;
		$this->deducible = false;
		$this->habilitado = true;
	}

	/**
	 * Initializes internal state of BaseAccidente object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [idchofer] column value.
	 * 
	 * @return     int
	 */
	public function getIdchofer()
	{
		return $this->idchofer;
	}

	/**
	 * Get the [idmovil] column value.
	 * 
	 * @return     int
	 */
	public function getIdmovil()
	{
		return $this->idmovil;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFecha($format = 'Y-m-d')
	{
		if ($this->fecha === null) {
			return null;
		}


		if ($this->fecha === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [responsable] column value.
	 * 
	 * @return     string
	 */
	public function getResponsable()
	{
		return $this->responsable;
	}

	/**
	 * Get the [esquina] column value.
	 * 
	 * @return     string
	 */
	public function getEsquina()
	{
		return $this->esquina;
	}

	/**
	 * Get the [heridos] column value.
	 * 
	 * @return     int
	 */
	public function getHeridos()
	{
		return $this->heridos;
	}

	/**
	 * Get the [deducible] column value.
	 * 
	 * @return     boolean
	 */
	public function getDeducible()
	{
		return $this->deducible;
	}

	/**
	 * Get the [descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getDescripcion()
	{
		return $this->descripcion;
	}

	/**
	 * Get the [optionally formatted] temporal [fechaalta] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaalta($format = 'Y-m-d H:i:s')
	{
		if ($this->fechaalta === null) {
			return null;
		}


		if ($this->fechaalta === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fechaalta);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fechaalta, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fechabaja] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechabaja($format = 'Y-m-d H:i:s')
	{
		if ($this->fechabaja === null) {
			return null;
		}


		if ($this->fechabaja === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fechabaja);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fechabaja, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [habilitado] column value.
	 * 
	 * @return     boolean
	 */
	public function getHabilitado()
	{
		return $this->habilitado;
	}

	/**
	 * Get the [usuario] column value.
	 * 
	 * @return     int
	 */
	public function getUsuario()
	{
		return $this->usuario;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AccidentePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [idchofer] column.
	 * 
	 * @param      int $v new value
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setIdchofer($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->idchofer !== $v) {
			$this->idchofer = $v;
			$this->modifiedColumns[] = AccidentePeer::IDCHOFER;
		}

		if ($this->aChofer !== null && $this->aChofer->getId() !== $v) {
			$this->aChofer = null;
		}

		return $this;
	} // setIdchofer()

	/**
	 * Set the value of [idmovil] column.
	 * 
	 * @param      int $v new value
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setIdmovil($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->idmovil !== $v) {
			$this->idmovil = $v;
			$this->modifiedColumns[] = AccidentePeer::IDMOVIL;
		}

		if ($this->aMovil !== null && $this->aMovil->getId() !== $v) {
			$this->aMovil = null;
		}

		return $this;
	} // setIdmovil()

	/**
	 * Sets the value of [fecha] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setFecha($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha !== null && $tmpDt = new DateTime($this->fecha)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = AccidentePeer::FECHA;
			}
		} // if either are not null

		return $this;
	} // setFecha()

	/**
	 * Set the value of [responsable] column.
	 * 
	 * @param      string $v new value
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setResponsable($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->responsable !== $v) {
			$this->responsable = $v;
			$this->modifiedColumns[] = AccidentePeer::RESPONSABLE;
		}

		return $this;
	} // setResponsable()

	/**
	 * Set the value of [esquina] column.
	 * 
	 * @param      string $v new value
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setEsquina($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->esquina !== $v) {
			$this->esquina = $v;
			$this->modifiedColumns[] = AccidentePeer::ESQUINA;
		}

		return $this;
	} // setEsquina()

	/**
	 * Set the value of [heridos] column.
	 * 
	 * @param      int $v new value
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setHeridos($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->heridos !== $v || $this->isNew()) {
			$this->heridos = $v;
			$this->modifiedColumns[] = AccidentePeer::HERIDOS;
		}

		return $this;
	} // setHeridos()

	/**
	 * Set the value of [deducible] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setDeducible($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->deducible !== $v || $this->isNew()) {
			$this->deducible = $v;
			$this->modifiedColumns[] = AccidentePeer::DEDUCIBLE;
		}

		return $this;
	} // setDeducible()

	/**
	 * Set the value of [descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcion !== $v) {
			$this->descripcion = $v;
			$this->modifiedColumns[] = AccidentePeer::DESCRIPCION;
		}

		return $this;
	} // setDescripcion()

	/**
	 * Sets the value of [fechaalta] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setFechaalta($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fechaalta !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fechaalta !== null && $tmpDt = new DateTime($this->fechaalta)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fechaalta = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AccidentePeer::FECHAALTA;
			}
		} // if either are not null

		return $this;
	} // setFechaalta()

	/**
	 * Sets the value of [fechabaja] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setFechabaja($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fechabaja !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fechabaja !== null && $tmpDt = new DateTime($this->fechabaja)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fechabaja = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AccidentePeer::FECHABAJA;
			}
		} // if either are not null

		return $this;
	} // setFechabaja()

	/**
	 * Set the value of [habilitado] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setHabilitado($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->habilitado !== $v || $this->isNew()) {
			$this->habilitado = $v;
			$this->modifiedColumns[] = AccidentePeer::HABILITADO;
		}

		return $this;
	} // setHabilitado()

	/**
	 * Set the value of [usuario] column.
	 * 
	 * @param      int $v new value
	 * @return     Accidente The current object (for fluent API support)
	 */
	public function setUsuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->usuario !== $v) {
			$this->usuario = $v;
			$this->modifiedColumns[] = AccidentePeer::USUARIO;
		}

		if ($this->aUsuarioRelatedByUsuario !== null && $this->aUsuarioRelatedByUsuario->getId() !== $v) {
			$this->aUsuarioRelatedByUsuario = null;
		}

		return $this;
	} // setUsuario()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->heridos !== 0) {
				return false;
			}

			if ($this->deducible !== false) {
				return false;
			}

			if ($this->habilitado !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->idchofer = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->idmovil = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->fecha = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->responsable = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->esquina = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->heridos = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->deducible = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
			$this->descripcion = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->fechaalta = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->fechabaja = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->habilitado = ($row[$startcol + 11] !== null) ? (boolean) $row[$startcol + 11] : null;
			$this->usuario = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 13; // 13 = AccidentePeer::NUM_COLUMNS - AccidentePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Accidente object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aChofer !== null && $this->idchofer !== $this->aChofer->getId()) {
			$this->aChofer = null;
		}
		if ($this->aMovil !== null && $this->idmovil !== $this->aMovil->getId()) {
			$this->aMovil = null;
		}
		if ($this->aUsuarioRelatedByUsuario !== null && $this->usuario !== $this->aUsuarioRelatedByUsuario->getId()) {
			$this->aUsuarioRelatedByUsuario = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AccidentePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AccidentePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aChofer = null;
			$this->aMovil = null;
			$this->aUsuarioRelatedByUsuario = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AccidentePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAccidente:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				AccidentePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAccidente:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AccidentePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAccidente:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAccidente:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				AccidentePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aChofer !== null) {
				if ($this->aChofer->isModified() || $this->aChofer->isNew()) {
					$affectedRows += $this->aChofer->save($con);
				}
				$this->setChofer($this->aChofer);
			}

			if ($this->aMovil !== null) {
				if ($this->aMovil->isModified() || $this->aMovil->isNew()) {
					$affectedRows += $this->aMovil->save($con);
				}
				$this->setMovil($this->aMovil);
			}

			if ($this->aUsuarioRelatedByUsuario !== null) {
				if ($this->aUsuarioRelatedByUsuario->isModified() || $this->aUsuarioRelatedByUsuario->isNew()) {
					$affectedRows += $this->aUsuarioRelatedByUsuario->save($con);
				}
				$this->setUsuarioRelatedByUsuario($this->aUsuarioRelatedByUsuario);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AccidentePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AccidentePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AccidentePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aChofer !== null) {
				if (!$this->aChofer->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aChofer->getValidationFailures());
				}
			}

			if ($this->aMovil !== null) {
				if (!$this->aMovil->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMovil->getValidationFailures());
				}
			}

			if ($this->aUsuarioRelatedByUsuario !== null) {
				if (!$this->aUsuarioRelatedByUsuario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuarioRelatedByUsuario->getValidationFailures());
				}
			}


			if (($retval = AccidentePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AccidentePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getIdchofer();
				break;
			case 2:
				return $this->getIdmovil();
				break;
			case 3:
				return $this->getFecha();
				break;
			case 4:
				return $this->getResponsable();
				break;
			case 5:
				return $this->getEsquina();
				break;
			case 6:
				return $this->getHeridos();
				break;
			case 7:
				return $this->getDeducible();
				break;
			case 8:
				return $this->getDescripcion();
				break;
			case 9:
				return $this->getFechaalta();
				break;
			case 10:
				return $this->getFechabaja();
				break;
			case 11:
				return $this->getHabilitado();
				break;
			case 12:
				return $this->getUsuario();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AccidentePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getIdchofer(),
			$keys[2] => $this->getIdmovil(),
			$keys[3] => $this->getFecha(),
			$keys[4] => $this->getResponsable(),
			$keys[5] => $this->getEsquina(),
			$keys[6] => $this->getHeridos(),
			$keys[7] => $this->getDeducible(),
			$keys[8] => $this->getDescripcion(),
			$keys[9] => $this->getFechaalta(),
			$keys[10] => $this->getFechabaja(),
			$keys[11] => $this->getHabilitado(),
			$keys[12] => $this->getUsuario(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AccidentePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setIdchofer($value);
				break;
			case 2:
				$this->setIdmovil($value);
				break;
			case 3:
				$this->setFecha($value);
				break;
			case 4:
				$this->setResponsable($value);
				break;
			case 5:
				$this->setEsquina($value);
				break;
			case 6:
				$this->setHeridos($value);
				break;
			case 7:
				$this->setDeducible($value);
				break;
			case 8:
				$this->setDescripcion($value);
				break;
			case 9:
				$this->setFechaalta($value);
				break;
			case 10:
				$this->setFechabaja($value);
				break;
			case 11:
				$this->setHabilitado($value);
				break;
			case 12:
				$this->setUsuario($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AccidentePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdchofer($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIdmovil($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFecha($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setResponsable($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setEsquina($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setHeridos($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDeducible($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDescripcion($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setFechaalta($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setFechabaja($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setHabilitado($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setUsuario($arr[$keys[12]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AccidentePeer::DATABASE_NAME);

		if ($this->isColumnModified(AccidentePeer::ID)) $criteria->add(AccidentePeer::ID, $this->id);
		if ($this->isColumnModified(AccidentePeer::IDCHOFER)) $criteria->add(AccidentePeer::IDCHOFER, $this->idchofer);
		if ($this->isColumnModified(AccidentePeer::IDMOVIL)) $criteria->add(AccidentePeer::IDMOVIL, $this->idmovil);
		if ($this->isColumnModified(AccidentePeer::FECHA)) $criteria->add(AccidentePeer::FECHA, $this->fecha);
		if ($this->isColumnModified(AccidentePeer::RESPONSABLE)) $criteria->add(AccidentePeer::RESPONSABLE, $this->responsable);
		if ($this->isColumnModified(AccidentePeer::ESQUINA)) $criteria->add(AccidentePeer::ESQUINA, $this->esquina);
		if ($this->isColumnModified(AccidentePeer::HERIDOS)) $criteria->add(AccidentePeer::HERIDOS, $this->heridos);
		if ($this->isColumnModified(AccidentePeer::DEDUCIBLE)) $criteria->add(AccidentePeer::DEDUCIBLE, $this->deducible);
		if ($this->isColumnModified(AccidentePeer::DESCRIPCION)) $criteria->add(AccidentePeer::DESCRIPCION, $this->descripcion);
		if ($this->isColumnModified(AccidentePeer::FECHAALTA)) $criteria->add(AccidentePeer::FECHAALTA, $this->fechaalta);
		if ($this->isColumnModified(AccidentePeer::FECHABAJA)) $criteria->add(AccidentePeer::FECHABAJA, $this->fechabaja);
		if ($this->isColumnModified(AccidentePeer::HABILITADO)) $criteria->add(AccidentePeer::HABILITADO, $this->habilitado);
		if ($this->isColumnModified(AccidentePeer::USUARIO)) $criteria->add(AccidentePeer::USUARIO, $this->usuario);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AccidentePeer::DATABASE_NAME);

		$criteria->add(AccidentePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Accidente (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdchofer($this->idchofer);

		$copyObj->setIdmovil($this->idmovil);

		$copyObj->setFecha($this->fecha);

		$copyObj->setResponsable($this->responsable);

		$copyObj->setEsquina($this->esquina);

		$copyObj->setHeridos($this->heridos);

		$copyObj->setDeducible($this->deducible);

		$copyObj->setDescripcion($this->descripcion);

		$copyObj->setFechaalta($this->fechaalta);

		$copyObj->setFechabaja($this->fechabaja);

		$copyObj->setHabilitado($this->habilitado);

		$copyObj->setUsuario($this->usuario);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Accidente Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AccidentePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AccidentePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Chofer object.
	 *
	 * @param      Chofer $v
	 * @return     Accidente The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setChofer(Chofer $v = null)
	{
		if ($v === null) {
			$this->setIdchofer(NULL);
		} else {
			$this->setIdchofer($v->getId());
		}

		$this->aChofer = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Chofer object, it will not be re-added.
		if ($v !== null) {
			$v->addAccidente($this);
		}

		return $this;
	}


	/**
	 * Get the associated Chofer object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Chofer The associated Chofer object.
	 * @throws     PropelException
	 */
	public function getChofer(PropelPDO $con = null)
	{
		if ($this->aChofer === null && ($this->idchofer !== null)) {
			$this->aChofer = ChoferPeer::retrieveByPk($this->idchofer);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aChofer->addAccidentes($this);
			 */
		}
		return $this->aChofer;
	}

	/**
	 * Declares an association between this object and a Movil object.
	 *
	 * @param      Movil $v
	 * @return     Accidente The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMovil(Movil $v = null)
	{
		if ($v === null) {
			$this->setIdmovil(NULL);
		} else {
			$this->setIdmovil($v->getId());
		}

		$this->aMovil = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Movil object, it will not be re-added.
		if ($v !== null) {
			$v->addAccidente($this);
		}

		return $this;
	}


	/**
	 * Get the associated Movil object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Movil The associated Movil object.
	 * @throws     PropelException
	 */
	public function getMovil(PropelPDO $con = null)
	{
		if ($this->aMovil === null && ($this->idmovil !== null)) {
			$this->aMovil = MovilPeer::retrieveByPk($this->idmovil);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMovil->addAccidentes($this);
			 */
		}
		return $this->aMovil;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     Accidente The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuarioRelatedByUsuario(Usuario $v = null)
	{
		if ($v === null) {
			$this->setUsuario(NULL);
		} else {
			$this->setUsuario($v->getId());
		}

		$this->aUsuarioRelatedByUsuario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addAccidente($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuarioRelatedByUsuario(PropelPDO $con = null)
	{
		if ($this->aUsuarioRelatedByUsuario === null && ($this->usuario !== null)) {
			$this->aUsuarioRelatedByUsuario = UsuarioPeer::retrieveByPk($this->usuario);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuarioRelatedByUsuario->addAccidentes($this);
			 */
		}
		return $this->aUsuarioRelatedByUsuario;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aChofer = null;
			$this->aMovil = null;
			$this->aUsuarioRelatedByUsuario = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseAccidente:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseAccidente::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseAccidente
