<?php

/**
 * Base class that represents a row from the 'configuracion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Oct  6 14:44:39 2012
 *
 * @package    lib.model.om
 */
abstract class BaseConfiguracion extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ConfiguracionPeer
	 */
	protected static $peer;

	/**
	 * The value for the idusuario field.
	 * @var        int
	 */
	protected $idusuario;

	/**
	 * The value for the fichanocturna field.
	 * @var        string
	 */
	protected $fichanocturna;

	/**
	 * The value for the fichadiurna field.
	 * @var        string
	 */
	protected $fichadiurna;

	/**
	 * The value for the banderadiurna field.
	 * @var        string
	 */
	protected $banderadiurna;

	/**
	 * The value for the banderanocturna field.
	 * @var        string
	 */
	protected $banderanocturna;

	/**
	 * The value for the avisovencimiento field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $avisovencimiento;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * @var        Usuario
	 */
	protected $aUsuario;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ConfiguracionPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->avisovencimiento = true;
	}

	/**
	 * Initializes internal state of BaseConfiguracion object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [idusuario] column value.
	 * 
	 * @return     int
	 */
	public function getIdusuario()
	{
		return $this->idusuario;
	}

	/**
	 * Get the [fichanocturna] column value.
	 * 
	 * @return     string
	 */
	public function getFichanocturna()
	{
		return $this->fichanocturna;
	}

	/**
	 * Get the [fichadiurna] column value.
	 * 
	 * @return     string
	 */
	public function getFichadiurna()
	{
		return $this->fichadiurna;
	}

	/**
	 * Get the [banderadiurna] column value.
	 * 
	 * @return     string
	 */
	public function getBanderadiurna()
	{
		return $this->banderadiurna;
	}

	/**
	 * Get the [banderanocturna] column value.
	 * 
	 * @return     string
	 */
	public function getBanderanocturna()
	{
		return $this->banderanocturna;
	}

	/**
	 * Get the [avisovencimiento] column value.
	 * 
	 * @return     boolean
	 */
	public function getAvisovencimiento()
	{
		return $this->avisovencimiento;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set the value of [idusuario] column.
	 * 
	 * @param      int $v new value
	 * @return     Configuracion The current object (for fluent API support)
	 */
	public function setIdusuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->idusuario !== $v) {
			$this->idusuario = $v;
			$this->modifiedColumns[] = ConfiguracionPeer::IDUSUARIO;
		}

		if ($this->aUsuario !== null && $this->aUsuario->getId() !== $v) {
			$this->aUsuario = null;
		}

		return $this;
	} // setIdusuario()

	/**
	 * Set the value of [fichanocturna] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuracion The current object (for fluent API support)
	 */
	public function setFichanocturna($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fichanocturna !== $v) {
			$this->fichanocturna = $v;
			$this->modifiedColumns[] = ConfiguracionPeer::FICHANOCTURNA;
		}

		return $this;
	} // setFichanocturna()

	/**
	 * Set the value of [fichadiurna] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuracion The current object (for fluent API support)
	 */
	public function setFichadiurna($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fichadiurna !== $v) {
			$this->fichadiurna = $v;
			$this->modifiedColumns[] = ConfiguracionPeer::FICHADIURNA;
		}

		return $this;
	} // setFichadiurna()

	/**
	 * Set the value of [banderadiurna] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuracion The current object (for fluent API support)
	 */
	public function setBanderadiurna($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->banderadiurna !== $v) {
			$this->banderadiurna = $v;
			$this->modifiedColumns[] = ConfiguracionPeer::BANDERADIURNA;
		}

		return $this;
	} // setBanderadiurna()

	/**
	 * Set the value of [banderanocturna] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuracion The current object (for fluent API support)
	 */
	public function setBanderanocturna($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->banderanocturna !== $v) {
			$this->banderanocturna = $v;
			$this->modifiedColumns[] = ConfiguracionPeer::BANDERANOCTURNA;
		}

		return $this;
	} // setBanderanocturna()

	/**
	 * Set the value of [avisovencimiento] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Configuracion The current object (for fluent API support)
	 */
	public function setAvisovencimiento($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->avisovencimiento !== $v || $this->isNew()) {
			$this->avisovencimiento = $v;
			$this->modifiedColumns[] = ConfiguracionPeer::AVISOVENCIMIENTO;
		}

		return $this;
	} // setAvisovencimiento()

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Configuracion The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ConfiguracionPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->avisovencimiento !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->idusuario = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->fichanocturna = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->fichadiurna = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->banderadiurna = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->banderanocturna = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->avisovencimiento = ($row[$startcol + 5] !== null) ? (boolean) $row[$startcol + 5] : null;
			$this->id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = ConfiguracionPeer::NUM_COLUMNS - ConfiguracionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Configuracion object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsuario !== null && $this->idusuario !== $this->aUsuario->getId()) {
			$this->aUsuario = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ConfiguracionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ConfiguracionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUsuario = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ConfiguracionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseConfiguracion:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ConfiguracionPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseConfiguracion:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ConfiguracionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseConfiguracion:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseConfiguracion:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ConfiguracionPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsuario !== null) {
				if ($this->aUsuario->isModified() || $this->aUsuario->isNew()) {
					$affectedRows += $this->aUsuario->save($con);
				}
				$this->setUsuario($this->aUsuario);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ConfiguracionPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ConfiguracionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ConfiguracionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsuario !== null) {
				if (!$this->aUsuario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuario->getValidationFailures());
				}
			}


			if (($retval = ConfiguracionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ConfiguracionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdusuario();
				break;
			case 1:
				return $this->getFichanocturna();
				break;
			case 2:
				return $this->getFichadiurna();
				break;
			case 3:
				return $this->getBanderadiurna();
				break;
			case 4:
				return $this->getBanderanocturna();
				break;
			case 5:
				return $this->getAvisovencimiento();
				break;
			case 6:
				return $this->getId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ConfiguracionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdusuario(),
			$keys[1] => $this->getFichanocturna(),
			$keys[2] => $this->getFichadiurna(),
			$keys[3] => $this->getBanderadiurna(),
			$keys[4] => $this->getBanderanocturna(),
			$keys[5] => $this->getAvisovencimiento(),
			$keys[6] => $this->getId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ConfiguracionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdusuario($value);
				break;
			case 1:
				$this->setFichanocturna($value);
				break;
			case 2:
				$this->setFichadiurna($value);
				break;
			case 3:
				$this->setBanderadiurna($value);
				break;
			case 4:
				$this->setBanderanocturna($value);
				break;
			case 5:
				$this->setAvisovencimiento($value);
				break;
			case 6:
				$this->setId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ConfiguracionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdusuario($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setFichanocturna($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFichadiurna($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setBanderadiurna($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setBanderanocturna($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setAvisovencimiento($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setId($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ConfiguracionPeer::DATABASE_NAME);

		if ($this->isColumnModified(ConfiguracionPeer::IDUSUARIO)) $criteria->add(ConfiguracionPeer::IDUSUARIO, $this->idusuario);
		if ($this->isColumnModified(ConfiguracionPeer::FICHANOCTURNA)) $criteria->add(ConfiguracionPeer::FICHANOCTURNA, $this->fichanocturna);
		if ($this->isColumnModified(ConfiguracionPeer::FICHADIURNA)) $criteria->add(ConfiguracionPeer::FICHADIURNA, $this->fichadiurna);
		if ($this->isColumnModified(ConfiguracionPeer::BANDERADIURNA)) $criteria->add(ConfiguracionPeer::BANDERADIURNA, $this->banderadiurna);
		if ($this->isColumnModified(ConfiguracionPeer::BANDERANOCTURNA)) $criteria->add(ConfiguracionPeer::BANDERANOCTURNA, $this->banderanocturna);
		if ($this->isColumnModified(ConfiguracionPeer::AVISOVENCIMIENTO)) $criteria->add(ConfiguracionPeer::AVISOVENCIMIENTO, $this->avisovencimiento);
		if ($this->isColumnModified(ConfiguracionPeer::ID)) $criteria->add(ConfiguracionPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ConfiguracionPeer::DATABASE_NAME);

		$criteria->add(ConfiguracionPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Configuracion (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdusuario($this->idusuario);

		$copyObj->setFichanocturna($this->fichanocturna);

		$copyObj->setFichadiurna($this->fichadiurna);

		$copyObj->setBanderadiurna($this->banderadiurna);

		$copyObj->setBanderanocturna($this->banderanocturna);

		$copyObj->setAvisovencimiento($this->avisovencimiento);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Configuracion Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ConfiguracionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ConfiguracionPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     Configuracion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuario(Usuario $v = null)
	{
		if ($v === null) {
			$this->setIdusuario(NULL);
		} else {
			$this->setIdusuario($v->getId());
		}

		$this->aUsuario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addConfiguracion($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuario(PropelPDO $con = null)
	{
		if ($this->aUsuario === null && ($this->idusuario !== null)) {
			$this->aUsuario = UsuarioPeer::retrieveByPk($this->idusuario);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuario->addConfiguracions($this);
			 */
		}
		return $this->aUsuario;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aUsuario = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseConfiguracion:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseConfiguracion::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseConfiguracion
