<?php

/**
 * Base class that represents a row from the 'pagoAseguradora' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Oct  6 14:44:39 2012
 *
 * @package    lib.model.om
 */
abstract class BasePagoaseguradora extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PagoaseguradoraPeer
	 */
	protected static $peer;

	/**
	 * The value for the idempresa field.
	 * @var        int
	 */
	protected $idempresa;

	/**
	 * The value for the idaseguradora field.
	 * @var        int
	 */
	protected $idaseguradora;

	/**
	 * The value for the idmovil field.
	 * @var        int
	 */
	protected $idmovil;

	/**
	 * The value for the pagocorrespondiente field.
	 * @var        string
	 */
	protected $pagocorrespondiente;

	/**
	 * The value for the monto field.
	 * @var        string
	 */
	protected $monto;

	/**
	 * The value for the fechapago field.
	 * @var        string
	 */
	protected $fechapago;

	/**
	 * The value for the fechaalta field.
	 * @var        string
	 */
	protected $fechaalta;

	/**
	 * The value for the fechabaja field.
	 * @var        string
	 */
	protected $fechabaja;

	/**
	 * The value for the habilitado field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $habilitado;

	/**
	 * The value for the usuario field.
	 * @var        int
	 */
	protected $usuario;

	/**
	 * @var        Empresa
	 */
	protected $aEmpresa;

	/**
	 * @var        Aseguradora
	 */
	protected $aAseguradora;

	/**
	 * @var        Movil
	 */
	protected $aMovil;

	/**
	 * @var        Usuario
	 */
	protected $aUsuarioRelatedByUsuario;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'PagoaseguradoraPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->habilitado = true;
	}

	/**
	 * Initializes internal state of BasePagoaseguradora object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [idempresa] column value.
	 * 
	 * @return     int
	 */
	public function getIdempresa()
	{
		return $this->idempresa;
	}

	/**
	 * Get the [idaseguradora] column value.
	 * 
	 * @return     int
	 */
	public function getIdaseguradora()
	{
		return $this->idaseguradora;
	}

	/**
	 * Get the [idmovil] column value.
	 * 
	 * @return     int
	 */
	public function getIdmovil()
	{
		return $this->idmovil;
	}

	/**
	 * Get the [optionally formatted] temporal [pagocorrespondiente] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getPagocorrespondiente($format = 'Y-m-d')
	{
		if ($this->pagocorrespondiente === null) {
			return null;
		}


		if ($this->pagocorrespondiente === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->pagocorrespondiente);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->pagocorrespondiente, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [monto] column value.
	 * 
	 * @return     string
	 */
	public function getMonto()
	{
		return $this->monto;
	}

	/**
	 * Get the [optionally formatted] temporal [fechapago] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechapago($format = 'Y-m-d')
	{
		if ($this->fechapago === null) {
			return null;
		}


		if ($this->fechapago === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fechapago);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fechapago, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fechaalta] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaalta($format = 'Y-m-d H:i:s')
	{
		if ($this->fechaalta === null) {
			return null;
		}


		if ($this->fechaalta === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fechaalta);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fechaalta, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fechabaja] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechabaja($format = 'Y-m-d H:i:s')
	{
		if ($this->fechabaja === null) {
			return null;
		}


		if ($this->fechabaja === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fechabaja);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fechabaja, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [habilitado] column value.
	 * 
	 * @return     boolean
	 */
	public function getHabilitado()
	{
		return $this->habilitado;
	}

	/**
	 * Get the [usuario] column value.
	 * 
	 * @return     int
	 */
	public function getUsuario()
	{
		return $this->usuario;
	}

	/**
	 * Set the value of [idempresa] column.
	 * 
	 * @param      int $v new value
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 */
	public function setIdempresa($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->idempresa !== $v) {
			$this->idempresa = $v;
			$this->modifiedColumns[] = PagoaseguradoraPeer::IDEMPRESA;
		}

		if ($this->aEmpresa !== null && $this->aEmpresa->getId() !== $v) {
			$this->aEmpresa = null;
		}

		return $this;
	} // setIdempresa()

	/**
	 * Set the value of [idaseguradora] column.
	 * 
	 * @param      int $v new value
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 */
	public function setIdaseguradora($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->idaseguradora !== $v) {
			$this->idaseguradora = $v;
			$this->modifiedColumns[] = PagoaseguradoraPeer::IDASEGURADORA;
		}

		if ($this->aAseguradora !== null && $this->aAseguradora->getId() !== $v) {
			$this->aAseguradora = null;
		}

		return $this;
	} // setIdaseguradora()

	/**
	 * Set the value of [idmovil] column.
	 * 
	 * @param      int $v new value
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 */
	public function setIdmovil($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->idmovil !== $v) {
			$this->idmovil = $v;
			$this->modifiedColumns[] = PagoaseguradoraPeer::IDMOVIL;
		}

		if ($this->aMovil !== null && $this->aMovil->getId() !== $v) {
			$this->aMovil = null;
		}

		return $this;
	} // setIdmovil()

	/**
	 * Sets the value of [pagocorrespondiente] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 */
	public function setPagocorrespondiente($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->pagocorrespondiente !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->pagocorrespondiente !== null && $tmpDt = new DateTime($this->pagocorrespondiente)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->pagocorrespondiente = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = PagoaseguradoraPeer::PAGOCORRESPONDIENTE;
			}
		} // if either are not null

		return $this;
	} // setPagocorrespondiente()

	/**
	 * Set the value of [monto] column.
	 * 
	 * @param      string $v new value
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 */
	public function setMonto($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->monto !== $v) {
			$this->monto = $v;
			$this->modifiedColumns[] = PagoaseguradoraPeer::MONTO;
		}

		return $this;
	} // setMonto()

	/**
	 * Sets the value of [fechapago] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 */
	public function setFechapago($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fechapago !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fechapago !== null && $tmpDt = new DateTime($this->fechapago)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fechapago = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = PagoaseguradoraPeer::FECHAPAGO;
			}
		} // if either are not null

		return $this;
	} // setFechapago()

	/**
	 * Sets the value of [fechaalta] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 */
	public function setFechaalta($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fechaalta !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fechaalta !== null && $tmpDt = new DateTime($this->fechaalta)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fechaalta = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PagoaseguradoraPeer::FECHAALTA;
			}
		} // if either are not null

		return $this;
	} // setFechaalta()

	/**
	 * Sets the value of [fechabaja] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 */
	public function setFechabaja($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fechabaja !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fechabaja !== null && $tmpDt = new DateTime($this->fechabaja)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fechabaja = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PagoaseguradoraPeer::FECHABAJA;
			}
		} // if either are not null

		return $this;
	} // setFechabaja()

	/**
	 * Set the value of [habilitado] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 */
	public function setHabilitado($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->habilitado !== $v || $this->isNew()) {
			$this->habilitado = $v;
			$this->modifiedColumns[] = PagoaseguradoraPeer::HABILITADO;
		}

		return $this;
	} // setHabilitado()

	/**
	 * Set the value of [usuario] column.
	 * 
	 * @param      int $v new value
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 */
	public function setUsuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->usuario !== $v) {
			$this->usuario = $v;
			$this->modifiedColumns[] = PagoaseguradoraPeer::USUARIO;
		}

		if ($this->aUsuarioRelatedByUsuario !== null && $this->aUsuarioRelatedByUsuario->getId() !== $v) {
			$this->aUsuarioRelatedByUsuario = null;
		}

		return $this;
	} // setUsuario()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->habilitado !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->idempresa = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->idaseguradora = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->idmovil = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->pagocorrespondiente = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->monto = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->fechapago = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->fechaalta = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->fechabaja = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->habilitado = ($row[$startcol + 8] !== null) ? (boolean) $row[$startcol + 8] : null;
			$this->usuario = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = PagoaseguradoraPeer::NUM_COLUMNS - PagoaseguradoraPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Pagoaseguradora object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aEmpresa !== null && $this->idempresa !== $this->aEmpresa->getId()) {
			$this->aEmpresa = null;
		}
		if ($this->aAseguradora !== null && $this->idaseguradora !== $this->aAseguradora->getId()) {
			$this->aAseguradora = null;
		}
		if ($this->aMovil !== null && $this->idmovil !== $this->aMovil->getId()) {
			$this->aMovil = null;
		}
		if ($this->aUsuarioRelatedByUsuario !== null && $this->usuario !== $this->aUsuarioRelatedByUsuario->getId()) {
			$this->aUsuarioRelatedByUsuario = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PagoaseguradoraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PagoaseguradoraPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aEmpresa = null;
			$this->aAseguradora = null;
			$this->aMovil = null;
			$this->aUsuarioRelatedByUsuario = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PagoaseguradoraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePagoaseguradora:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				PagoaseguradoraPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePagoaseguradora:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PagoaseguradoraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePagoaseguradora:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePagoaseguradora:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				PagoaseguradoraPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEmpresa !== null) {
				if ($this->aEmpresa->isModified() || $this->aEmpresa->isNew()) {
					$affectedRows += $this->aEmpresa->save($con);
				}
				$this->setEmpresa($this->aEmpresa);
			}

			if ($this->aAseguradora !== null) {
				if ($this->aAseguradora->isModified() || $this->aAseguradora->isNew()) {
					$affectedRows += $this->aAseguradora->save($con);
				}
				$this->setAseguradora($this->aAseguradora);
			}

			if ($this->aMovil !== null) {
				if ($this->aMovil->isModified() || $this->aMovil->isNew()) {
					$affectedRows += $this->aMovil->save($con);
				}
				$this->setMovil($this->aMovil);
			}

			if ($this->aUsuarioRelatedByUsuario !== null) {
				if ($this->aUsuarioRelatedByUsuario->isModified() || $this->aUsuarioRelatedByUsuario->isNew()) {
					$affectedRows += $this->aUsuarioRelatedByUsuario->save($con);
				}
				$this->setUsuarioRelatedByUsuario($this->aUsuarioRelatedByUsuario);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PagoaseguradoraPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += PagoaseguradoraPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEmpresa !== null) {
				if (!$this->aEmpresa->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEmpresa->getValidationFailures());
				}
			}

			if ($this->aAseguradora !== null) {
				if (!$this->aAseguradora->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAseguradora->getValidationFailures());
				}
			}

			if ($this->aMovil !== null) {
				if (!$this->aMovil->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMovil->getValidationFailures());
				}
			}

			if ($this->aUsuarioRelatedByUsuario !== null) {
				if (!$this->aUsuarioRelatedByUsuario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuarioRelatedByUsuario->getValidationFailures());
				}
			}


			if (($retval = PagoaseguradoraPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PagoaseguradoraPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdempresa();
				break;
			case 1:
				return $this->getIdaseguradora();
				break;
			case 2:
				return $this->getIdmovil();
				break;
			case 3:
				return $this->getPagocorrespondiente();
				break;
			case 4:
				return $this->getMonto();
				break;
			case 5:
				return $this->getFechapago();
				break;
			case 6:
				return $this->getFechaalta();
				break;
			case 7:
				return $this->getFechabaja();
				break;
			case 8:
				return $this->getHabilitado();
				break;
			case 9:
				return $this->getUsuario();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PagoaseguradoraPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdempresa(),
			$keys[1] => $this->getIdaseguradora(),
			$keys[2] => $this->getIdmovil(),
			$keys[3] => $this->getPagocorrespondiente(),
			$keys[4] => $this->getMonto(),
			$keys[5] => $this->getFechapago(),
			$keys[6] => $this->getFechaalta(),
			$keys[7] => $this->getFechabaja(),
			$keys[8] => $this->getHabilitado(),
			$keys[9] => $this->getUsuario(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PagoaseguradoraPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdempresa($value);
				break;
			case 1:
				$this->setIdaseguradora($value);
				break;
			case 2:
				$this->setIdmovil($value);
				break;
			case 3:
				$this->setPagocorrespondiente($value);
				break;
			case 4:
				$this->setMonto($value);
				break;
			case 5:
				$this->setFechapago($value);
				break;
			case 6:
				$this->setFechaalta($value);
				break;
			case 7:
				$this->setFechabaja($value);
				break;
			case 8:
				$this->setHabilitado($value);
				break;
			case 9:
				$this->setUsuario($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PagoaseguradoraPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdempresa($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdaseguradora($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIdmovil($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPagocorrespondiente($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setMonto($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFechapago($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFechaalta($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setFechabaja($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setHabilitado($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUsuario($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PagoaseguradoraPeer::DATABASE_NAME);

		if ($this->isColumnModified(PagoaseguradoraPeer::IDEMPRESA)) $criteria->add(PagoaseguradoraPeer::IDEMPRESA, $this->idempresa);
		if ($this->isColumnModified(PagoaseguradoraPeer::IDASEGURADORA)) $criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->idaseguradora);
		if ($this->isColumnModified(PagoaseguradoraPeer::IDMOVIL)) $criteria->add(PagoaseguradoraPeer::IDMOVIL, $this->idmovil);
		if ($this->isColumnModified(PagoaseguradoraPeer::PAGOCORRESPONDIENTE)) $criteria->add(PagoaseguradoraPeer::PAGOCORRESPONDIENTE, $this->pagocorrespondiente);
		if ($this->isColumnModified(PagoaseguradoraPeer::MONTO)) $criteria->add(PagoaseguradoraPeer::MONTO, $this->monto);
		if ($this->isColumnModified(PagoaseguradoraPeer::FECHAPAGO)) $criteria->add(PagoaseguradoraPeer::FECHAPAGO, $this->fechapago);
		if ($this->isColumnModified(PagoaseguradoraPeer::FECHAALTA)) $criteria->add(PagoaseguradoraPeer::FECHAALTA, $this->fechaalta);
		if ($this->isColumnModified(PagoaseguradoraPeer::FECHABAJA)) $criteria->add(PagoaseguradoraPeer::FECHABAJA, $this->fechabaja);
		if ($this->isColumnModified(PagoaseguradoraPeer::HABILITADO)) $criteria->add(PagoaseguradoraPeer::HABILITADO, $this->habilitado);
		if ($this->isColumnModified(PagoaseguradoraPeer::USUARIO)) $criteria->add(PagoaseguradoraPeer::USUARIO, $this->usuario);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PagoaseguradoraPeer::DATABASE_NAME);

		$criteria->add(PagoaseguradoraPeer::IDEMPRESA, $this->idempresa);
		$criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->idaseguradora);
		$criteria->add(PagoaseguradoraPeer::IDMOVIL, $this->idmovil);
		$criteria->add(PagoaseguradoraPeer::PAGOCORRESPONDIENTE, $this->pagocorrespondiente);

		return $criteria;
	}

	/**
	 * Returns the composite primary key for this object.
	 * The array elements will be in same order as specified in XML.
	 * @return     array
	 */
	public function getPrimaryKey()
	{
		$pks = array();

		$pks[0] = $this->getIdempresa();

		$pks[1] = $this->getIdaseguradora();

		$pks[2] = $this->getIdmovil();

		$pks[3] = $this->getPagocorrespondiente();

		return $pks;
	}

	/**
	 * Set the [composite] primary key.
	 *
	 * @param      array $keys The elements of the composite key (order must match the order in XML file).
	 * @return     void
	 */
	public function setPrimaryKey($keys)
	{

		$this->setIdempresa($keys[0]);

		$this->setIdaseguradora($keys[1]);

		$this->setIdmovil($keys[2]);

		$this->setPagocorrespondiente($keys[3]);

	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Pagoaseguradora (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdempresa($this->idempresa);

		$copyObj->setIdaseguradora($this->idaseguradora);

		$copyObj->setIdmovil($this->idmovil);

		$copyObj->setPagocorrespondiente($this->pagocorrespondiente);

		$copyObj->setMonto($this->monto);

		$copyObj->setFechapago($this->fechapago);

		$copyObj->setFechaalta($this->fechaalta);

		$copyObj->setFechabaja($this->fechabaja);

		$copyObj->setHabilitado($this->habilitado);

		$copyObj->setUsuario($this->usuario);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Pagoaseguradora Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PagoaseguradoraPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PagoaseguradoraPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Empresa object.
	 *
	 * @param      Empresa $v
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEmpresa(Empresa $v = null)
	{
		if ($v === null) {
			$this->setIdempresa(NULL);
		} else {
			$this->setIdempresa($v->getId());
		}

		$this->aEmpresa = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Empresa object, it will not be re-added.
		if ($v !== null) {
			$v->addPagoaseguradora($this);
		}

		return $this;
	}


	/**
	 * Get the associated Empresa object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Empresa The associated Empresa object.
	 * @throws     PropelException
	 */
	public function getEmpresa(PropelPDO $con = null)
	{
		if ($this->aEmpresa === null && ($this->idempresa !== null)) {
			$this->aEmpresa = EmpresaPeer::retrieveByPk($this->idempresa);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEmpresa->addPagoaseguradoras($this);
			 */
		}
		return $this->aEmpresa;
	}

	/**
	 * Declares an association between this object and a Aseguradora object.
	 *
	 * @param      Aseguradora $v
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAseguradora(Aseguradora $v = null)
	{
		if ($v === null) {
			$this->setIdaseguradora(NULL);
		} else {
			$this->setIdaseguradora($v->getId());
		}

		$this->aAseguradora = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Aseguradora object, it will not be re-added.
		if ($v !== null) {
			$v->addPagoaseguradora($this);
		}

		return $this;
	}


	/**
	 * Get the associated Aseguradora object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Aseguradora The associated Aseguradora object.
	 * @throws     PropelException
	 */
	public function getAseguradora(PropelPDO $con = null)
	{
		if ($this->aAseguradora === null && ($this->idaseguradora !== null)) {
			$this->aAseguradora = AseguradoraPeer::retrieveByPk($this->idaseguradora);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAseguradora->addPagoaseguradoras($this);
			 */
		}
		return $this->aAseguradora;
	}

	/**
	 * Declares an association between this object and a Movil object.
	 *
	 * @param      Movil $v
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMovil(Movil $v = null)
	{
		if ($v === null) {
			$this->setIdmovil(NULL);
		} else {
			$this->setIdmovil($v->getId());
		}

		$this->aMovil = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Movil object, it will not be re-added.
		if ($v !== null) {
			$v->addPagoaseguradora($this);
		}

		return $this;
	}


	/**
	 * Get the associated Movil object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Movil The associated Movil object.
	 * @throws     PropelException
	 */
	public function getMovil(PropelPDO $con = null)
	{
		if ($this->aMovil === null && ($this->idmovil !== null)) {
			$this->aMovil = MovilPeer::retrieveByPk($this->idmovil);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMovil->addPagoaseguradoras($this);
			 */
		}
		return $this->aMovil;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     Pagoaseguradora The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuarioRelatedByUsuario(Usuario $v = null)
	{
		if ($v === null) {
			$this->setUsuario(NULL);
		} else {
			$this->setUsuario($v->getId());
		}

		$this->aUsuarioRelatedByUsuario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addPagoaseguradora($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuarioRelatedByUsuario(PropelPDO $con = null)
	{
		if ($this->aUsuarioRelatedByUsuario === null && ($this->usuario !== null)) {
			$this->aUsuarioRelatedByUsuario = UsuarioPeer::retrieveByPk($this->usuario);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuarioRelatedByUsuario->addPagoaseguradoras($this);
			 */
		}
		return $this->aUsuarioRelatedByUsuario;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aEmpresa = null;
			$this->aAseguradora = null;
			$this->aMovil = null;
			$this->aUsuarioRelatedByUsuario = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePagoaseguradora:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePagoaseguradora::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BasePagoaseguradora
