<?php

/**
 * Base class that represents a row from the 'aseguradora' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jun 10 22:16:03 2013
 *
 * @package    lib.model.om
 */
abstract class BaseAseguradora extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AseguradoraPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the nombre field.
	 * @var        string
	 */
	protected $nombre;

	/**
	 * The value for the direccion field.
	 * @var        string
	 */
	protected $direccion;

	/**
	 * The value for the telefono field.
	 * @var        string
	 */
	protected $telefono;

	/**
	 * The value for the telefono2 field.
	 * @var        string
	 */
	protected $telefono2;

	/**
	 * The value for the telefono3 field.
	 * @var        string
	 */
	protected $telefono3;

	/**
	 * The value for the web field.
	 * @var        string
	 */
	protected $web;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the fechaalta field.
	 * @var        string
	 */
	protected $fechaalta;

	/**
	 * The value for the fechabaja field.
	 * @var        string
	 */
	protected $fechabaja;

	/**
	 * The value for the habilitado field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $habilitado;

	/**
	 * The value for the usuario field.
	 * @var        int
	 */
	protected $usuario;

	/**
	 * @var        Usuario
	 */
	protected $aUsuarioRelatedByUsuario;

	/**
	 * @var        array Movil[] Collection to store aggregation of Movil objects.
	 */
	protected $collMovils;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMovils.
	 */
	private $lastMovilCriteria = null;

	/**
	 * @var        array Pagoaseguradora[] Collection to store aggregation of Pagoaseguradora objects.
	 */
	protected $collPagoaseguradoras;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPagoaseguradoras.
	 */
	private $lastPagoaseguradoraCriteria = null;

	/**
	 * @var        array MovilAseguradora[] Collection to store aggregation of MovilAseguradora objects.
	 */
	protected $collMovilAseguradoras;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMovilAseguradoras.
	 */
	private $lastMovilAseguradoraCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'AseguradoraPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->habilitado = true;
	}

	/**
	 * Initializes internal state of BaseAseguradora object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [nombre] column value.
	 * 
	 * @return     string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Get the [direccion] column value.
	 * 
	 * @return     string
	 */
	public function getDireccion()
	{
		return $this->direccion;
	}

	/**
	 * Get the [telefono] column value.
	 * 
	 * @return     string
	 */
	public function getTelefono()
	{
		return $this->telefono;
	}

	/**
	 * Get the [telefono2] column value.
	 * 
	 * @return     string
	 */
	public function getTelefono2()
	{
		return $this->telefono2;
	}

	/**
	 * Get the [telefono3] column value.
	 * 
	 * @return     string
	 */
	public function getTelefono3()
	{
		return $this->telefono3;
	}

	/**
	 * Get the [web] column value.
	 * 
	 * @return     string
	 */
	public function getWeb()
	{
		return $this->web;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [optionally formatted] temporal [fechaalta] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaalta($format = 'Y-m-d H:i:s')
	{
		if ($this->fechaalta === null) {
			return null;
		}


		if ($this->fechaalta === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fechaalta);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fechaalta, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fechabaja] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechabaja($format = 'Y-m-d H:i:s')
	{
		if ($this->fechabaja === null) {
			return null;
		}


		if ($this->fechabaja === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fechabaja);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fechabaja, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [habilitado] column value.
	 * 
	 * @return     boolean
	 */
	public function getHabilitado()
	{
		return $this->habilitado;
	}

	/**
	 * Get the [usuario] column value.
	 * 
	 * @return     int
	 */
	public function getUsuario()
	{
		return $this->usuario;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AseguradoraPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre !== $v) {
			$this->nombre = $v;
			$this->modifiedColumns[] = AseguradoraPeer::NOMBRE;
		}

		return $this;
	} // setNombre()

	/**
	 * Set the value of [direccion] column.
	 * 
	 * @param      string $v new value
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setDireccion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->direccion !== $v) {
			$this->direccion = $v;
			$this->modifiedColumns[] = AseguradoraPeer::DIRECCION;
		}

		return $this;
	} // setDireccion()

	/**
	 * Set the value of [telefono] column.
	 * 
	 * @param      string $v new value
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setTelefono($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telefono !== $v) {
			$this->telefono = $v;
			$this->modifiedColumns[] = AseguradoraPeer::TELEFONO;
		}

		return $this;
	} // setTelefono()

	/**
	 * Set the value of [telefono2] column.
	 * 
	 * @param      string $v new value
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setTelefono2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telefono2 !== $v) {
			$this->telefono2 = $v;
			$this->modifiedColumns[] = AseguradoraPeer::TELEFONO2;
		}

		return $this;
	} // setTelefono2()

	/**
	 * Set the value of [telefono3] column.
	 * 
	 * @param      string $v new value
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setTelefono3($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telefono3 !== $v) {
			$this->telefono3 = $v;
			$this->modifiedColumns[] = AseguradoraPeer::TELEFONO3;
		}

		return $this;
	} // setTelefono3()

	/**
	 * Set the value of [web] column.
	 * 
	 * @param      string $v new value
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setWeb($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->web !== $v) {
			$this->web = $v;
			$this->modifiedColumns[] = AseguradoraPeer::WEB;
		}

		return $this;
	} // setWeb()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = AseguradoraPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Sets the value of [fechaalta] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setFechaalta($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fechaalta !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fechaalta !== null && $tmpDt = new DateTime($this->fechaalta)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fechaalta = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AseguradoraPeer::FECHAALTA;
			}
		} // if either are not null

		return $this;
	} // setFechaalta()

	/**
	 * Sets the value of [fechabaja] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setFechabaja($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fechabaja !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fechabaja !== null && $tmpDt = new DateTime($this->fechabaja)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fechabaja = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AseguradoraPeer::FECHABAJA;
			}
		} // if either are not null

		return $this;
	} // setFechabaja()

	/**
	 * Set the value of [habilitado] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setHabilitado($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->habilitado !== $v || $this->isNew()) {
			$this->habilitado = $v;
			$this->modifiedColumns[] = AseguradoraPeer::HABILITADO;
		}

		return $this;
	} // setHabilitado()

	/**
	 * Set the value of [usuario] column.
	 * 
	 * @param      int $v new value
	 * @return     Aseguradora The current object (for fluent API support)
	 */
	public function setUsuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->usuario !== $v) {
			$this->usuario = $v;
			$this->modifiedColumns[] = AseguradoraPeer::USUARIO;
		}

		if ($this->aUsuarioRelatedByUsuario !== null && $this->aUsuarioRelatedByUsuario->getId() !== $v) {
			$this->aUsuarioRelatedByUsuario = null;
		}

		return $this;
	} // setUsuario()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->habilitado !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->nombre = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->direccion = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->telefono = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->telefono2 = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->telefono3 = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->web = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->email = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->fechaalta = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->fechabaja = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->habilitado = ($row[$startcol + 10] !== null) ? (boolean) $row[$startcol + 10] : null;
			$this->usuario = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = AseguradoraPeer::NUM_COLUMNS - AseguradoraPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Aseguradora object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsuarioRelatedByUsuario !== null && $this->usuario !== $this->aUsuarioRelatedByUsuario->getId()) {
			$this->aUsuarioRelatedByUsuario = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AseguradoraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AseguradoraPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUsuarioRelatedByUsuario = null;
			$this->collMovils = null;
			$this->lastMovilCriteria = null;

			$this->collPagoaseguradoras = null;
			$this->lastPagoaseguradoraCriteria = null;

			$this->collMovilAseguradoras = null;
			$this->lastMovilAseguradoraCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AseguradoraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAseguradora:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				AseguradoraPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAseguradora:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AseguradoraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAseguradora:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAseguradora:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				AseguradoraPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsuarioRelatedByUsuario !== null) {
				if ($this->aUsuarioRelatedByUsuario->isModified() || $this->aUsuarioRelatedByUsuario->isNew()) {
					$affectedRows += $this->aUsuarioRelatedByUsuario->save($con);
				}
				$this->setUsuarioRelatedByUsuario($this->aUsuarioRelatedByUsuario);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AseguradoraPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AseguradoraPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AseguradoraPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collMovils !== null) {
				foreach ($this->collMovils as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPagoaseguradoras !== null) {
				foreach ($this->collPagoaseguradoras as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMovilAseguradoras !== null) {
				foreach ($this->collMovilAseguradoras as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsuarioRelatedByUsuario !== null) {
				if (!$this->aUsuarioRelatedByUsuario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuarioRelatedByUsuario->getValidationFailures());
				}
			}


			if (($retval = AseguradoraPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collMovils !== null) {
					foreach ($this->collMovils as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPagoaseguradoras !== null) {
					foreach ($this->collPagoaseguradoras as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMovilAseguradoras !== null) {
					foreach ($this->collMovilAseguradoras as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AseguradoraPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNombre();
				break;
			case 2:
				return $this->getDireccion();
				break;
			case 3:
				return $this->getTelefono();
				break;
			case 4:
				return $this->getTelefono2();
				break;
			case 5:
				return $this->getTelefono3();
				break;
			case 6:
				return $this->getWeb();
				break;
			case 7:
				return $this->getEmail();
				break;
			case 8:
				return $this->getFechaalta();
				break;
			case 9:
				return $this->getFechabaja();
				break;
			case 10:
				return $this->getHabilitado();
				break;
			case 11:
				return $this->getUsuario();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AseguradoraPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNombre(),
			$keys[2] => $this->getDireccion(),
			$keys[3] => $this->getTelefono(),
			$keys[4] => $this->getTelefono2(),
			$keys[5] => $this->getTelefono3(),
			$keys[6] => $this->getWeb(),
			$keys[7] => $this->getEmail(),
			$keys[8] => $this->getFechaalta(),
			$keys[9] => $this->getFechabaja(),
			$keys[10] => $this->getHabilitado(),
			$keys[11] => $this->getUsuario(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AseguradoraPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNombre($value);
				break;
			case 2:
				$this->setDireccion($value);
				break;
			case 3:
				$this->setTelefono($value);
				break;
			case 4:
				$this->setTelefono2($value);
				break;
			case 5:
				$this->setTelefono3($value);
				break;
			case 6:
				$this->setWeb($value);
				break;
			case 7:
				$this->setEmail($value);
				break;
			case 8:
				$this->setFechaalta($value);
				break;
			case 9:
				$this->setFechabaja($value);
				break;
			case 10:
				$this->setHabilitado($value);
				break;
			case 11:
				$this->setUsuario($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AseguradoraPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNombre($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDireccion($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTelefono($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTelefono2($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTelefono3($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setWeb($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setEmail($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFechaalta($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setFechabaja($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setHabilitado($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setUsuario($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);

		if ($this->isColumnModified(AseguradoraPeer::ID)) $criteria->add(AseguradoraPeer::ID, $this->id);
		if ($this->isColumnModified(AseguradoraPeer::NOMBRE)) $criteria->add(AseguradoraPeer::NOMBRE, $this->nombre);
		if ($this->isColumnModified(AseguradoraPeer::DIRECCION)) $criteria->add(AseguradoraPeer::DIRECCION, $this->direccion);
		if ($this->isColumnModified(AseguradoraPeer::TELEFONO)) $criteria->add(AseguradoraPeer::TELEFONO, $this->telefono);
		if ($this->isColumnModified(AseguradoraPeer::TELEFONO2)) $criteria->add(AseguradoraPeer::TELEFONO2, $this->telefono2);
		if ($this->isColumnModified(AseguradoraPeer::TELEFONO3)) $criteria->add(AseguradoraPeer::TELEFONO3, $this->telefono3);
		if ($this->isColumnModified(AseguradoraPeer::WEB)) $criteria->add(AseguradoraPeer::WEB, $this->web);
		if ($this->isColumnModified(AseguradoraPeer::EMAIL)) $criteria->add(AseguradoraPeer::EMAIL, $this->email);
		if ($this->isColumnModified(AseguradoraPeer::FECHAALTA)) $criteria->add(AseguradoraPeer::FECHAALTA, $this->fechaalta);
		if ($this->isColumnModified(AseguradoraPeer::FECHABAJA)) $criteria->add(AseguradoraPeer::FECHABAJA, $this->fechabaja);
		if ($this->isColumnModified(AseguradoraPeer::HABILITADO)) $criteria->add(AseguradoraPeer::HABILITADO, $this->habilitado);
		if ($this->isColumnModified(AseguradoraPeer::USUARIO)) $criteria->add(AseguradoraPeer::USUARIO, $this->usuario);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);

		$criteria->add(AseguradoraPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Aseguradora (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNombre($this->nombre);

		$copyObj->setDireccion($this->direccion);

		$copyObj->setTelefono($this->telefono);

		$copyObj->setTelefono2($this->telefono2);

		$copyObj->setTelefono3($this->telefono3);

		$copyObj->setWeb($this->web);

		$copyObj->setEmail($this->email);

		$copyObj->setFechaalta($this->fechaalta);

		$copyObj->setFechabaja($this->fechabaja);

		$copyObj->setHabilitado($this->habilitado);

		$copyObj->setUsuario($this->usuario);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getMovils() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMovil($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPagoaseguradoras() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPagoaseguradora($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMovilAseguradoras() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMovilAseguradora($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Aseguradora Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AseguradoraPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AseguradoraPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     Aseguradora The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuarioRelatedByUsuario(Usuario $v = null)
	{
		if ($v === null) {
			$this->setUsuario(NULL);
		} else {
			$this->setUsuario($v->getId());
		}

		$this->aUsuarioRelatedByUsuario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addAseguradora($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuarioRelatedByUsuario(PropelPDO $con = null)
	{
		if ($this->aUsuarioRelatedByUsuario === null && ($this->usuario !== null)) {
			$this->aUsuarioRelatedByUsuario = UsuarioPeer::retrieveByPk($this->usuario);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuarioRelatedByUsuario->addAseguradoras($this);
			 */
		}
		return $this->aUsuarioRelatedByUsuario;
	}

	/**
	 * Clears out the collMovils collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMovils()
	 */
	public function clearMovils()
	{
		$this->collMovils = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMovils collection (array).
	 *
	 * By default this just sets the collMovils collection to an empty array (like clearcollMovils());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMovils()
	{
		$this->collMovils = array();
	}

	/**
	 * Gets an array of Movil objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Aseguradora has previously been saved, it will retrieve
	 * related Movils from storage. If this Aseguradora is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Movil[]
	 * @throws     PropelException
	 */
	public function getMovils($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMovils === null) {
			if ($this->isNew()) {
			   $this->collMovils = array();
			} else {

				$criteria->add(MovilPeer::IDASEGURADORA, $this->id);

				MovilPeer::addSelectColumns($criteria);
				$this->collMovils = MovilPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MovilPeer::IDASEGURADORA, $this->id);

				MovilPeer::addSelectColumns($criteria);
				if (!isset($this->lastMovilCriteria) || !$this->lastMovilCriteria->equals($criteria)) {
					$this->collMovils = MovilPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMovilCriteria = $criteria;
		return $this->collMovils;
	}

	/**
	 * Returns the number of related Movil objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Movil objects.
	 * @throws     PropelException
	 */
	public function countMovils(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMovils === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MovilPeer::IDASEGURADORA, $this->id);

				$count = MovilPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MovilPeer::IDASEGURADORA, $this->id);

				if (!isset($this->lastMovilCriteria) || !$this->lastMovilCriteria->equals($criteria)) {
					$count = MovilPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collMovils);
				}
			} else {
				$count = count($this->collMovils);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Movil object to this object
	 * through the Movil foreign key attribute.
	 *
	 * @param      Movil $l Movil
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMovil(Movil $l)
	{
		if ($this->collMovils === null) {
			$this->initMovils();
		}
		if (!in_array($l, $this->collMovils, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMovils, $l);
			$l->setAseguradora($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aseguradora is new, it will return
	 * an empty collection; or if this Aseguradora has previously
	 * been saved, it will retrieve related Movils from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aseguradora.
	 */
	public function getMovilsJoinDespacho($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMovils === null) {
			if ($this->isNew()) {
				$this->collMovils = array();
			} else {

				$criteria->add(MovilPeer::IDASEGURADORA, $this->id);

				$this->collMovils = MovilPeer::doSelectJoinDespacho($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MovilPeer::IDASEGURADORA, $this->id);

			if (!isset($this->lastMovilCriteria) || !$this->lastMovilCriteria->equals($criteria)) {
				$this->collMovils = MovilPeer::doSelectJoinDespacho($criteria, $con, $join_behavior);
			}
		}
		$this->lastMovilCriteria = $criteria;

		return $this->collMovils;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aseguradora is new, it will return
	 * an empty collection; or if this Aseguradora has previously
	 * been saved, it will retrieve related Movils from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aseguradora.
	 */
	public function getMovilsJoinUsuarioRelatedByUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMovils === null) {
			if ($this->isNew()) {
				$this->collMovils = array();
			} else {

				$criteria->add(MovilPeer::IDASEGURADORA, $this->id);

				$this->collMovils = MovilPeer::doSelectJoinUsuarioRelatedByUsuario($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MovilPeer::IDASEGURADORA, $this->id);

			if (!isset($this->lastMovilCriteria) || !$this->lastMovilCriteria->equals($criteria)) {
				$this->collMovils = MovilPeer::doSelectJoinUsuarioRelatedByUsuario($criteria, $con, $join_behavior);
			}
		}
		$this->lastMovilCriteria = $criteria;

		return $this->collMovils;
	}

	/**
	 * Clears out the collPagoaseguradoras collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPagoaseguradoras()
	 */
	public function clearPagoaseguradoras()
	{
		$this->collPagoaseguradoras = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPagoaseguradoras collection (array).
	 *
	 * By default this just sets the collPagoaseguradoras collection to an empty array (like clearcollPagoaseguradoras());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPagoaseguradoras()
	{
		$this->collPagoaseguradoras = array();
	}

	/**
	 * Gets an array of Pagoaseguradora objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Aseguradora has previously been saved, it will retrieve
	 * related Pagoaseguradoras from storage. If this Aseguradora is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Pagoaseguradora[]
	 * @throws     PropelException
	 */
	public function getPagoaseguradoras($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPagoaseguradoras === null) {
			if ($this->isNew()) {
			   $this->collPagoaseguradoras = array();
			} else {

				$criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->id);

				PagoaseguradoraPeer::addSelectColumns($criteria);
				$this->collPagoaseguradoras = PagoaseguradoraPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->id);

				PagoaseguradoraPeer::addSelectColumns($criteria);
				if (!isset($this->lastPagoaseguradoraCriteria) || !$this->lastPagoaseguradoraCriteria->equals($criteria)) {
					$this->collPagoaseguradoras = PagoaseguradoraPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPagoaseguradoraCriteria = $criteria;
		return $this->collPagoaseguradoras;
	}

	/**
	 * Returns the number of related Pagoaseguradora objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Pagoaseguradora objects.
	 * @throws     PropelException
	 */
	public function countPagoaseguradoras(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPagoaseguradoras === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->id);

				$count = PagoaseguradoraPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->id);

				if (!isset($this->lastPagoaseguradoraCriteria) || !$this->lastPagoaseguradoraCriteria->equals($criteria)) {
					$count = PagoaseguradoraPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPagoaseguradoras);
				}
			} else {
				$count = count($this->collPagoaseguradoras);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Pagoaseguradora object to this object
	 * through the Pagoaseguradora foreign key attribute.
	 *
	 * @param      Pagoaseguradora $l Pagoaseguradora
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPagoaseguradora(Pagoaseguradora $l)
	{
		if ($this->collPagoaseguradoras === null) {
			$this->initPagoaseguradoras();
		}
		if (!in_array($l, $this->collPagoaseguradoras, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPagoaseguradoras, $l);
			$l->setAseguradora($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aseguradora is new, it will return
	 * an empty collection; or if this Aseguradora has previously
	 * been saved, it will retrieve related Pagoaseguradoras from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aseguradora.
	 */
	public function getPagoaseguradorasJoinEmpresa($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPagoaseguradoras === null) {
			if ($this->isNew()) {
				$this->collPagoaseguradoras = array();
			} else {

				$criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->id);

				$this->collPagoaseguradoras = PagoaseguradoraPeer::doSelectJoinEmpresa($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->id);

			if (!isset($this->lastPagoaseguradoraCriteria) || !$this->lastPagoaseguradoraCriteria->equals($criteria)) {
				$this->collPagoaseguradoras = PagoaseguradoraPeer::doSelectJoinEmpresa($criteria, $con, $join_behavior);
			}
		}
		$this->lastPagoaseguradoraCriteria = $criteria;

		return $this->collPagoaseguradoras;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aseguradora is new, it will return
	 * an empty collection; or if this Aseguradora has previously
	 * been saved, it will retrieve related Pagoaseguradoras from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aseguradora.
	 */
	public function getPagoaseguradorasJoinMovil($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPagoaseguradoras === null) {
			if ($this->isNew()) {
				$this->collPagoaseguradoras = array();
			} else {

				$criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->id);

				$this->collPagoaseguradoras = PagoaseguradoraPeer::doSelectJoinMovil($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->id);

			if (!isset($this->lastPagoaseguradoraCriteria) || !$this->lastPagoaseguradoraCriteria->equals($criteria)) {
				$this->collPagoaseguradoras = PagoaseguradoraPeer::doSelectJoinMovil($criteria, $con, $join_behavior);
			}
		}
		$this->lastPagoaseguradoraCriteria = $criteria;

		return $this->collPagoaseguradoras;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aseguradora is new, it will return
	 * an empty collection; or if this Aseguradora has previously
	 * been saved, it will retrieve related Pagoaseguradoras from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aseguradora.
	 */
	public function getPagoaseguradorasJoinUsuarioRelatedByUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPagoaseguradoras === null) {
			if ($this->isNew()) {
				$this->collPagoaseguradoras = array();
			} else {

				$criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->id);

				$this->collPagoaseguradoras = PagoaseguradoraPeer::doSelectJoinUsuarioRelatedByUsuario($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PagoaseguradoraPeer::IDASEGURADORA, $this->id);

			if (!isset($this->lastPagoaseguradoraCriteria) || !$this->lastPagoaseguradoraCriteria->equals($criteria)) {
				$this->collPagoaseguradoras = PagoaseguradoraPeer::doSelectJoinUsuarioRelatedByUsuario($criteria, $con, $join_behavior);
			}
		}
		$this->lastPagoaseguradoraCriteria = $criteria;

		return $this->collPagoaseguradoras;
	}

	/**
	 * Clears out the collMovilAseguradoras collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMovilAseguradoras()
	 */
	public function clearMovilAseguradoras()
	{
		$this->collMovilAseguradoras = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMovilAseguradoras collection (array).
	 *
	 * By default this just sets the collMovilAseguradoras collection to an empty array (like clearcollMovilAseguradoras());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMovilAseguradoras()
	{
		$this->collMovilAseguradoras = array();
	}

	/**
	 * Gets an array of MovilAseguradora objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Aseguradora has previously been saved, it will retrieve
	 * related MovilAseguradoras from storage. If this Aseguradora is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array MovilAseguradora[]
	 * @throws     PropelException
	 */
	public function getMovilAseguradoras($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMovilAseguradoras === null) {
			if ($this->isNew()) {
			   $this->collMovilAseguradoras = array();
			} else {

				$criteria->add(MovilAseguradoraPeer::IDASEGURADORA, $this->id);

				MovilAseguradoraPeer::addSelectColumns($criteria);
				$this->collMovilAseguradoras = MovilAseguradoraPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MovilAseguradoraPeer::IDASEGURADORA, $this->id);

				MovilAseguradoraPeer::addSelectColumns($criteria);
				if (!isset($this->lastMovilAseguradoraCriteria) || !$this->lastMovilAseguradoraCriteria->equals($criteria)) {
					$this->collMovilAseguradoras = MovilAseguradoraPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMovilAseguradoraCriteria = $criteria;
		return $this->collMovilAseguradoras;
	}

	/**
	 * Returns the number of related MovilAseguradora objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related MovilAseguradora objects.
	 * @throws     PropelException
	 */
	public function countMovilAseguradoras(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMovilAseguradoras === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MovilAseguradoraPeer::IDASEGURADORA, $this->id);

				$count = MovilAseguradoraPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MovilAseguradoraPeer::IDASEGURADORA, $this->id);

				if (!isset($this->lastMovilAseguradoraCriteria) || !$this->lastMovilAseguradoraCriteria->equals($criteria)) {
					$count = MovilAseguradoraPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collMovilAseguradoras);
				}
			} else {
				$count = count($this->collMovilAseguradoras);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a MovilAseguradora object to this object
	 * through the MovilAseguradora foreign key attribute.
	 *
	 * @param      MovilAseguradora $l MovilAseguradora
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMovilAseguradora(MovilAseguradora $l)
	{
		if ($this->collMovilAseguradoras === null) {
			$this->initMovilAseguradoras();
		}
		if (!in_array($l, $this->collMovilAseguradoras, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMovilAseguradoras, $l);
			$l->setAseguradora($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aseguradora is new, it will return
	 * an empty collection; or if this Aseguradora has previously
	 * been saved, it will retrieve related MovilAseguradoras from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aseguradora.
	 */
	public function getMovilAseguradorasJoinMovil($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMovilAseguradoras === null) {
			if ($this->isNew()) {
				$this->collMovilAseguradoras = array();
			} else {

				$criteria->add(MovilAseguradoraPeer::IDASEGURADORA, $this->id);

				$this->collMovilAseguradoras = MovilAseguradoraPeer::doSelectJoinMovil($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MovilAseguradoraPeer::IDASEGURADORA, $this->id);

			if (!isset($this->lastMovilAseguradoraCriteria) || !$this->lastMovilAseguradoraCriteria->equals($criteria)) {
				$this->collMovilAseguradoras = MovilAseguradoraPeer::doSelectJoinMovil($criteria, $con, $join_behavior);
			}
		}
		$this->lastMovilAseguradoraCriteria = $criteria;

		return $this->collMovilAseguradoras;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aseguradora is new, it will return
	 * an empty collection; or if this Aseguradora has previously
	 * been saved, it will retrieve related MovilAseguradoras from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aseguradora.
	 */
	public function getMovilAseguradorasJoinUsuarioRelatedByUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AseguradoraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMovilAseguradoras === null) {
			if ($this->isNew()) {
				$this->collMovilAseguradoras = array();
			} else {

				$criteria->add(MovilAseguradoraPeer::IDASEGURADORA, $this->id);

				$this->collMovilAseguradoras = MovilAseguradoraPeer::doSelectJoinUsuarioRelatedByUsuario($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MovilAseguradoraPeer::IDASEGURADORA, $this->id);

			if (!isset($this->lastMovilAseguradoraCriteria) || !$this->lastMovilAseguradoraCriteria->equals($criteria)) {
				$this->collMovilAseguradoras = MovilAseguradoraPeer::doSelectJoinUsuarioRelatedByUsuario($criteria, $con, $join_behavior);
			}
		}
		$this->lastMovilAseguradoraCriteria = $criteria;

		return $this->collMovilAseguradoras;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collMovils) {
				foreach ((array) $this->collMovils as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPagoaseguradoras) {
				foreach ((array) $this->collPagoaseguradoras as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMovilAseguradoras) {
				foreach ((array) $this->collMovilAseguradoras as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collMovils = null;
		$this->collPagoaseguradoras = null;
		$this->collMovilAseguradoras = null;
			$this->aUsuarioRelatedByUsuario = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseAseguradora:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseAseguradora::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseAseguradora
