<?php

namespace TaxiAdmin\PropietarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PropietarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropietarioRepository extends EntityRepository
{
}
