<?php

namespace TaxiAdmin\MovilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovilRepository extends EntityRepository {

    /**
     * obtengo todas los moviles para paginado
     */
    public function getIndexDQL($idUsuario){
        $sql = 'SELECT m
        FROM TaxiAdminMovilBundle:Movil m
        WHERE m.idUsuario = :idUsuario'; 

        $params = array(
            'idUsuario' => $idUsuario,
            );

        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameters($params);

        return $query;
    }
}
