<?php

namespace TaxiAdmin\MovilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovilRepository extends EntityRepository
{
}
