<?php

/**
 * Skeleton subclass for performing query and update operations on the 'accidente' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 17 11:18:29 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AccidentePeer extends BaseAccidentePeer {

    public static function getAccidenteByPK($pk, $idUsuario) {
        $criteria = new Criteria();
        $criteria->add(AccidentePeer::ID, $pk);
        $criteria->add(AccidentePeer::USUARIO, $idUsuario);
        $accidente = AccidentePeer::doSelectOne($criteria);
        return $accidente;
    }

}

// AccidentePeer
