<?php

/**
 * Skeleton subclass for performing query and update operations on the 'adelanto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 17 11:18:30 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AdelantoPeer extends BaseAdelantoPeer {

    public static function getAdelantoByPK($pk, $idUsuario) {
        $criteria = new Criteria();
        $criteria->add(AdelantoPeer::ID, $pk);
        $criteria->add(AdelantoPeer::USUARIO, $idUsuario);
        $adelanto = AdelantoPeer::doSelectOne($criteria);
        return $adelanto;
    }

}

// AdelantoPeer
