<?php

/**
 * Skeleton subclass for performing query and update operations on the 'chofer_empresa' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 17 11:18:31 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ChoferEmpresaPeer extends BaseChoferEmpresaPeer {

    public static function getByChofer($idChofer, $habilitado) {
        $criteria = new Criteria();
        $criteria->add(ChoferEmpresaPeer::HABILITADO, $habilitado);
        $criteria->add(ChoferEmpresaPeer::IDCHOFER, $idChofer);
        $listaChoferEmpresa = ChoferEmpresaPeer::doSelect($criteria);
        return $listaChoferEmpresa;
    }

    /**
     * Retorna para una empresa y un estado de habilitado todos los choferes que esta tiene
     * @param int $idEmpresa identificador de la empresa
     * @param int $habilitados estado de la relación y está activa o no
     * @return ChoferEmpresa[]
     */
    public static function getByEmpresa($idEmpresa, $habilitado) {
        $criteria = new Criteria();
        $criteria->add(ChoferEmpresaPeer::IDEMPRESA, $idEmpresa);
        $criteria->add(ChoferEmpresaPeer::HABILITADO, $habilitado);
        $listaChoferEmpresa = ChoferEmpresaPeer::doSelect($criteria);
        return $listaChoferEmpresa;
    }

    /**
     * Para una empresa y chofer retorna el objeto que representa esa relación
     * @param int $idEmpresa identificador empresa
     * @param int $idChofer identificador chofer
     * @return ChoferEmpresa en caso de no existir la relacion se retorna null
     */
    public static function getByChoferEmpresa($idEmpresa, $idChofer) {
        $criteria = new Criteria();
        $criteria->add(ChoferEmpresaPeer::IDEMPRESA, $idEmpresa);
        $criteria->add(ChoferEmpresaPeer::IDCHOFER, $idChofer);
        $empresaChofer = ChoferEmpresaPeer::doSelectOne($criteria);
        return $empresaChofer;
    }

}

// ChoferEmpresaPeer
