<?php

/**
 * Skeleton subclass for performing query and update operations on the 'despacho' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May  2 22:45:42 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DespachoPeer extends BaseDespachoPeer {

    public static function getHabilitadas() {
        $criteria = new Criteria();
        $criteria->add(DespachoPeer::HABILITADO, true);
        $despachos = DespachoPeer::doSelect($criteria);
        return $despachos;
    }

}

// DespachoPeer
