<?php

/**
 * Skeleton subclass for performing query and update operations on the 'empresa_propietario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 17 11:18:30 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EmpresaPropietarioPeer extends BaseEmpresaPropietarioPeer {

    public static function getByPropietario($idPropietario, $habilitado) {
        $criteria = new Criteria();
        $criteria->add(EmpresaPropietarioPeer::HABILITADO, $habilitado);
        $criteria->add(EmpresaPropietarioPeer::IDPROPIETARIO, $idPropietario);
        $listaEmpresaPropietario = EmpresaPropietarioPeer::doSelect($criteria);
        return $listaEmpresaPropietario;
    }

    public static function getByEmpresa($idEmpresa, $habilitado) {
        $criteria = new Criteria();
        $criteria->add(EmpresaPropietarioPeer::IDEMPRESA, $idEmpresa);
        $criteria->add(EmpresaPropietarioPeer::HABILITADO, $habilitado);
        $listaEmpresaPropietario = EmpresaPropietarioPeer::doSelect($criteria);
        return $listaEmpresaPropietario;
    }

    // retorna el objeto que tiene como clave el id de la empresa y el id del propietario

    /**
     *
     * @param     $idEmpresa Id de la empresa a buscar
     * @param      $idPropietario Id dle propietario a buscar
     * @return     el objeto EmpresaPropietario que contiene la relación de empresa propietario solicitado
     * @throws     PropelException Any exceptions caught during processing will be
     * 		 rethrown wrapped into a PropelException.
     */
    public static function getByPropietariosEmpresa($idEmpresa, $idPropietario) {
        $criteria = new Criteria();
        $criteria->add(EmpresaPropietarioPeer::IDEMPRESA, $idEmpresa);
        $criteria->add(EmpresaPropietarioPeer::IDPROPIETARIO, $idPropietario);
        $empresaPropietario = EmpresaPropietarioPeer::doSelectOne($criteria);
        return $empresaPropietario;
    }

}

// EmpresaPropietarioPeer
