<?php

/**
 * Skeleton subclass for performing query and update operations on the 'empresa' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 17 11:18:28 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EmpresaPeer extends BaseEmpresaPeer {

    public static function getByUsuario($idUsuario) {
        $criteria = new Criteria();
        $criteria->add(EmpresaPeer::USUARIO, $idUsuario);
        $criteria->add(EmpresaPeer::HABILITADO, TRUE);
        $empresas = EmpresaPeer::doSelect($criteria);
        return $empresas;
    }

    public static function getEmpresasParaUsuarioCriteria($idUsuario) {
        $criteria = new Criteria();
        $criteria->add(EmpresaPeer::USUARIO, $idUsuario);
        $criteria->add(EmpresaPeer::HABILITADO, TRUE);
        return $criteria;
    }

    // retorno la empresa cuyo nombre y razon social coincidan
    public static function getEmpresaByNombreAndRazonSocial($nombre, $razonSocial, $idUsuario) {
        $criteria = new Criteria();
        $criteria->add(EmpresaPeer ::NOMBRE, $nombre);
        $criteria->add(EmpresaPeer ::RAZONSOCIAL, $razonSocial);
        $criteria->add(EmpresaPeer ::USUARIO, $idUsuario);
        $empresa = EmpresaPeer ::doSelect($criteria);
        return $empresa;
    }

    public static function getEmpresaByPK($pk, $idUsuario) {
        $criteria = new Criteria();
        $criteria->add(EmpresaPeer::ID, $pk);
        $criteria->add(EmpresaPeer::USUARIO, $idUsuario);
        $empresa = EmpresaPeer::doSelectOne($criteria);
        return $empresa;
    }

}

// EmpresaPeer
