<?php

/**
 * Skeleton subclass for representing a row from the 'evento' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Mar 18 23:27:38 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Evento extends BaseEvento {

    public static function crearEvento($idUsuario, $texto) {
        $Evento = new Evento();
        $Evento->setIdusuario($idUsuario);
        $Evento->setEvento($texto);
        $Evento->setFecha("now");
        $Evento->save();
    }

}

// Evento
