<?php

/**
 * Skeleton subclass for performing query and update operations on the 'gastoMovil' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jul 23 21:41:50 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class GastomovilPeer extends BaseGastomovilPeer {

    public static function getGastoMovilByPK($pk, $idUsuario) {
        $criteria = new Criteria();
        $criteria->add(GastomovilPeer::ID, $pk);
        $criteria->add(GastomovilPeer::USUARIO, $idUsuario);
        $gastoMovil = GastomovilPeer::doSelectOne($criteria);
        return $gastoMovil;
    }

}

// GastomovilPeer
