<?php


/**
 * Skeleton subclass for performing query and update operations on the 'pagoAdelanto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 17 11:18:30 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PagoadelantoPeer extends BasePagoadelantoPeer {

	public static function getPagoAdelantoByPK($pk, $idUsuario) {
		$criteria = new Criteria();
		$criteria->add(PagoadelantoPeer::ID, $pk);
		$criteria->add(PagoadelantoPeer::USUARIO, $idUsuario);
		$pago = PagoadelantoPeer::doSelectOne($criteria);
		return $pago;
	}

} // PagoadelantoPeer
