<?php

/**
 * Skeleton subclass for representing a row from the 'propietario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 17 11:18:28 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Propietario extends BasePropietario {

    /**
     * Initializes internal state of Propietario object.
     * @see        parent::__construct()
     */
    public function __construct() {
        // Make sure that parent constructor is always invoked, since that
        // is where any default values for this object are set.
        parent::__construct();
    }

    public function __toString() {
        return $this->getNombre();
    }

    public function getEmpresas() {
        $empresas = array();

        $listaEmpresaPropietario = EmpresaPropietarioPeer::getByPropietario($this->getId(), TRUE);
        foreach ($listaEmpresaPropietario as $empresaPropietario) {
            array_push($empresas, $empresaPropietario->getEmpresa());
        }

        return $empresas;
    }

}

// Propietario
