<?php

/**
 * Skeleton subclass for performing query and update operations on the 'recaudacion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Jul 14 17:57:13 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class RecaudacionPeer extends BaseRecaudacionPeer {

    public static function getRecaudacionByPK($pk, $idUsuario) {
        $criteria = new Criteria();
        $criteria->add(RecaudacionPeer::ID, $pk);
        $criteria->add(RecaudacionPeer::USUARIO, $idUsuario);
        $recaudacion = RecaudacionPeer::doSelectOne($criteria);
        return $recaudacion;
    }

    public static function getRecaudacionesParaUsuarioCriteria($idUsuario, $idMovil, $idChofer) {
        $criteria = new Criteria();
        if($idMovil != null) {
            $criteria->add(RecaudacionPeer::IDMOVIL, $idMovil);
        }
        if($idChofer != null) {
            $criteria->add(RecaudacionPeer::IDCHOFER, $idChofer);
        }
        $criteria->add(RecaudacionPeer::USUARIO, $idUsuario);
        $criteria->add(RecaudacionPeer::HABILITADO, TRUE);
        $criteria->addDescendingOrderByColumn(RecaudacionPeer::FECHA);
        return $criteria;
    }

}

// RecaudacionPeer
