<?php

/**
 * Skeleton subclass for representing a row from the 'recaudacion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Jul 14 17:57:13 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Recaudacion extends BaseRecaudacion {

    /**
     * Initializes internal state of Recaudacion object.
     * @see        parent::__construct()
     */
    public function __construct() {
        // Make sure that parent constructor is always invoked, since that
        // is where any default values for this object are set.
        parent::__construct();
    }

    public function getFecha($format = 'Y-m-d') {
        // cambio el format por el que utilizamos en la aplicacion
        $format = ConstantesFrontEnd::$FORMAT_DATE;
        return parent::getFecha($format);
    }

    /**
     * 
     */
    public function getGasto($desc){
        $gasto = new Gastorecaudacion();
        $i = 0;
        $lista = $this->getGastorecaudacions();
        while ( $i < count($lista)) {
            if($lista[$i]->getDetalle() === $desc){
                $gasto = $lista[$i];
                $i = count($lista);
            }
            $i += 1;
        }
        return $gasto;
    }


}

// Recaudacion
