<?php


/**
 * Skeleton subclass for representing a row from the 'trabajoTaller' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Jul 14 15:52:49 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Trabajotaller extends BaseTrabajotaller {

	/**
	 * Initializes internal state of Trabajotaller object.
	 * @see        parent::__construct()
	 */
	public function __construct(){
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

	public function getFechaingreso($format = 'Y-m-d'){
		// cambio el format por el que utilizamos en la aplicacion
		$format = ConstantesFrontEnd::$FORMAT_DATE;
		return parent::getFechaingreso($format);
	}

} // Trabajotaller
