<?php

/**
 * Skeleton subclass for performing query and update operations on the 'trabajoTaller' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Jul 14 15:52:49 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TrabajotallerPeer extends BaseTrabajotallerPeer {

    public static function getTrabajoTallerByPK($pk, $idUsuario) {
        $criteria = new Criteria();
        $criteria->add(TrabajotallerPeer::ID, $pk);
        $criteria->add(TrabajotallerPeer::USUARIO, $idUsuario);
        $trabajoTaller = TrabajotallerPeer::doSelectOne($criteria);
        return $trabajoTaller;
    }

}

// TrabajotallerPeer
