<?php

/**
 * Skeleton subclass for performing query and update operations on the 'usuario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 17 11:18:28 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UsuarioPeer extends BaseUsuarioPeer {

    //retorna el usuario por el correo
    public static function getUsuario($correo) {
        $criteria = new Criteria();
        $criteria->add(UsuarioPeer::EMAIL, $correo);
        $usuarios = UsuarioPeer::doSelect($criteria);
        if (count($usuarios) > 0) {
            return $usuarios[0];
        } else {
            return null;
        }
    }

}

// UsuarioPeer
