parameters:
#    taxi_admin_usuario.example.class: TaxiAdmin\UsuarioBundle\Example

services:
#    taxi_admin_usuario.example:
#        class: %taxi_admin_usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
