<?php

namespace TaxiAdmin\ChoferBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdelantoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdelantoRepository extends EntityRepository
{
}
