
default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    language:     es
    #robots:       index, follow

  stylesheets:    [app.css, jquery-ui-1.8.21.custom.css, error.css]

  javascripts:    [jquery-1.7.2.min.js, jquery.livequery.js, jquery-ui-1.8.21.custom.min.js]

  has_layout:     true
  layout:         layout
